# NUMPY

1. Import numpy as np and print the version number.

In [2]:
# To check the version of numpy package
import numpy as np
np.__version__

'1.16.2'

2. Create a 1D array of numbers from 0 to 9

In [3]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a 3×3 numpy array of all True’s(1's)

In [4]:
a1=np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
a1<5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

4. Convert a 1D array to a 2D array with 2 rows

In [73]:
a3=np.arange(8)
a3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [74]:
a3.resize(2,4)
a3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
a3.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

5. Write a NumPy program to generate six random integers between 10 and 30

In [51]:
a4=np.random.randint(10,30,6)
a4

array([13, 10, 14, 19, 11, 24])

6. Write a NumPy program to create a 3x3x3 array with random values

In [11]:
a5=np.random.randn(3,3,3)
a5

array([[[ 0.00289985, -0.48786103, -0.31365942],
        [ 0.85951348, -0.7543543 ,  1.19547786],
        [ 0.78288947,  0.58438995,  0.97334958]],

       [[ 1.62093673, -0.18202066,  1.58224693],
        [-1.82298239,  0.68998615, -0.56104688],
        [-0.95802341, -0.58102526,  1.01245738]],

       [[ 0.66429926, -0.88737216, -0.67830104],
        [-0.06477296, -1.68011064,  0.53524184],
        [-0.26701756, -0.59412541,  0.63722748]]])

7.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values

In [20]:
a6=np.random.random((5,2))
a6

array([[0.09777799, 0.99458546],
       [0.11042986, 0.40991127],
       [0.75733439, 0.75073403],
       [0.62005974, 0.81877611],
       [0.45563461, 0.60867815]])

In [22]:
print(a6.min())
print(a6.max())

0.09777798706916996
0.9945854619339961


### 8 Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [31]:
a7=np.random.random((10,4))
a7[:5]

array([[0.21877704, 0.51546442, 0.54458649, 0.3414008 ],
       [0.16917116, 0.61825219, 0.72881193, 0.81085858],
       [0.60769025, 0.21036799, 0.99034799, 0.71390978],
       [0.07466423, 0.10993864, 0.53143992, 0.90830303],
       [0.78690021, 0.84332276, 0.77641887, 0.76641765]])

In [26]:
a7.reshape(2,5,4)

array([[[0.63953579, 0.70119765, 0.80484142, 0.81828022],
        [0.52428905, 0.07638791, 0.9916336 , 0.37473911],
        [0.65509053, 0.64814365, 0.73860492, 0.37994066],
        [0.31771669, 0.7463935 , 0.76680561, 0.973792  ],
        [0.4221653 , 0.79015605, 0.07853928, 0.68548809]],

       [[0.13922476, 0.03950538, 0.06377193, 0.9959435 ],
        [0.01855737, 0.96631779, 0.34292173, 0.50023766],
        [0.41104151, 0.32927108, 0.02123619, 0.77337591],
        [0.32414269, 0.21238203, 0.60482087, 0.98995663],
        [0.75865074, 0.66852828, 0.82154696, 0.72670594]]])

In [30]:
a=a7[:5]
a

array([[0.63953579, 0.70119765, 0.80484142, 0.81828022],
       [0.52428905, 0.07638791, 0.9916336 , 0.37473911],
       [0.65509053, 0.64814365, 0.73860492, 0.37994066],
       [0.31771669, 0.7463935 , 0.76680561, 0.973792  ],
       [0.4221653 , 0.79015605, 0.07853928, 0.68548809]])

### 9.How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
a = [[1,2,3],[2,3,4],[3,4,5]]

out = [[3,4,5],[2,3,4],[1,2,3]]

In [5]:
arr = np.arange(9).reshape(3,3) 
a = [[1,2,3],[2,3,4],[3,4,5]]
res = a[::-1]
res

[[3, 4, 5], [2, 3, 4], [1, 2, 3]]

### 10. Create 1D array with random numbers and replace all odd numbers in arr with -1

In [34]:
a1=np.arange(10)
a1
num =0
for i in range(len(a1)):
    if a1[i]%2 != 0:
        a1[i]=-1
a1        

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

SyntaxError: invalid syntax (<ipython-input-18-2730393b22c3>, line 1)